##################################
# Chloe B.'s Samba Configuration #
##################################

##########
# GLOBAL #
##########

[global]

# Use the standalone server role.
    server role = standalone

# Log file name formatted as: IP_YYYYMMDD_HHMMSS.log.
    log file = /var/log/samba/%J_%T.log

# Do not cap log file size.
    max log size = 0

# Enable the following virtual file system modules:
#     * audit         - cog client operations.
#     * fruit         - compatability for Apple SMB and Apple FP.
#     * streams_xattr - alternative data streams (ADS) support.
    vfs objects = audit fruit streams_xattr

##########
# SHARES #
##########

[homes]
    comment = Home Directories
    browseable = no
    writeable = yes
