###############################################
# Chloe B.'s (Private) Hyprlock Configuration #
###############################################

############
# MONITORS #
############

# ViewSonic Corporation XG271QG (Left)
$myLeftMonitorDescription = ViewSonic Corporation XG271QG

# ViewSonic Corporation VP2756-4K (Right)
$myRightMonitorDescription = ViewSonic Corporation VP2756-4K

# BOE 0x0BCA (Laptop)
$myLaptopMonitorDescription = BOE 0x0BCA

###########
# GENERAL #
###########

general {
    # Hide the cursor.
    hide_cursor = true

    # Skips validation if no password is provided.
    ignore_empty_input = true

    # Time (ms) to UI reset after a failed authentication.
    fail_timeout = 3000
}

##############
# ANIMATIONS #
##############

animations {
    # Enable animations.
    enabled = true

    # Set the Bezier curve.
    bezier = ease-in-out, 0.42, 0.00, 0.58, 1.00

    # Set the fade animations.
    animation = fade, 1, 5, ease-in-out

    # Set the fade animations for input-field's colors.
    animation = inputFieldColors, 1, 5, ease-in-out
}

###########
# WIDGETS #
###########

background {
    # Set the background to black.
    color = rgba(0, 0, 0, 1.0)

    # Blur the background.
    blur_passes = 3

    # Disable adding noise to the blur.
    noise = 0.0

    # Disable contrast modulation.
    contrast = 1.0

    # Set the brightness of the blurred image to 25%.
    brightness = 0.25

    # Disable vibrancy modulation.
    vibrancy = 1.0
}

input-field {
    # Display the input field on one monitor.
    monitor = $myLeftMonitorDescription

    # Set the size of the input field (circle on 16:9 displays).
    size = 13.5%, 24%

    # Set the outline thickness.
    outline_thickness = 10

    # Set the outer color.
    outer_color = rgba(63, 63, 63, 1.0)

    # Remove the inner color.
    inner_color = rgba(0, 0, 0, 0.50)

    # Disable fading on empty.
    fade_on_empty = false

    # Remove the placeholder text.
    placeholder_text = 

    # Hide input, but with an indicator.
    hide_input = true

    # Set the base color for the input indicator.
    hide_input_base_color = rgba(102, 138, 171, 1.0)

    # Enable complete rounding (circle on 16:9 displays).
    rounding = -1

    # Set the processing (check) color.
    check_color = rgba(245, 169, 184, 1.0)

    # Set the fail color.
    fail_color = rgba(165, 78, 86, 1.0)

    # Remove the fail text.
    fail_text = 

    # Set the horizontal alignment.
    halign = center

    # Set the vertical alignment.
    valign = center
}
